import { Inter } from 'next/font/google';
import './globals.css';
import { DbProvider } from '../db/dbContext';

const inter = Inter({ subsets: ['latin'] });

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <DbProvider>
        <body className={inter.className}>{children}</body>
      </DbProvider>
    </html>
  );
}

export default RootLayout;